README.md
project.clj
src/asami/core.cljc
test/asami/test_memory.cljc

Fixed TX bug

---

project.clj
src/asami/core.cljc
src/asami/graph.cljc
src/asami/index.cljc
src/asami/multi_graph.cljc
src/asami/query.cljc
test/asami/test_core.cljc
test/asami/test_memory_index.cljc
test/asami/test_multi_graph.cljc
test/asami/test_query.cljc

Added multi-graphs.
Added retraction operations.
Fixed query syntax for filters.
Added functionality for bindings, and minus operations, though not yet in the planner.

Query features

---

project.clj
src/asami/core.cljc
src/asami/multi_graph.cljc

Bug fixes while still working on query features

Multigraph updates

---

project.clj
src/asami/core.cljc
src/asami/query.cljc
test/asami/test_query.cljc

Added bindings for :in clauses

Query bindings

---

src/asami/common_index.cljc
src/asami/graph.cljc
src/asami/index.cljc
src/asami/multi_graph.cljc
test/asami/test_transitive.cljc

Added transitive predicate support. Closes #36. This is partial implementation required for #37

Transitive Predicates

---

src/asami/analytics.cljc
src/asami/common_index.cljc
src/asami/graph.cljc
src/asami/index.cljc
src/asami/multi_graph.cljc
test/asami/test_analytics.cljc
test/asami/test_transitive.cljc

This implements the subgraph function, to identify all disjoint subgraphs in a graph

Full subgraph API

---

src/asami/core.cljc
src/asami/internal.cljc
src/asami/planner.cljc
src/asami/query.cljc
test/asami/test_api.cljc
test/asami/test_query_internals.cljc

Reintroduces options, particularly for query planning

Redo options

---

src/asami/query.cljc
test/asami/test_api.cljc

Fixed bugs in query rewrite and `and` operator

Added Optional operator

---

src/asami/planner.cljc
test/asami/test_planner.cljc

Correctly planning for optionals

Optional planner

---

CHANGELOG.md
project.clj
src/asami/core.cljc
src/asami/durable/codec.cljc
src/asami/durable/decoder.clj
src/asami/durable/encoder.clj
src/asami/durable/graph.cljc
src/asami/durable/store.cljc
src/asami/graph.cljc
src/asami/memory.cljc
src/asami/peer.clj
src/asami/query.cljc
src/asami/sandbox.cljc
src/asami/storage.cljc
test/asami/durable/codec_test.cljc
test/asami/durable/graph_test.cljc

Added internal nodes. Updated Zuko.

Internal nodes

---

project.clj
src/asami/core.cljc
src/asami/durable/store.cljc
src/asami/entities.cljc
src/asami/internal.cljc
src/asami/memory.cljc
src/asami/storage.cljc

encapsulating transaction operations more, and lock protection on durable connections

Concurrency fixes

---

CHANGELOG.md
README.md
project.clj
src/asami/core.cljc
src/asami/entities.cljc
test/asami/api_test.cljc
test/asami/durable/api_test.cljc

Incorporates new `:tg/owns` attribute for entities, and respects these for entity attribute updates

Bug zuko12

---

src/asami/durable/graph.cljc
src/asami/graph.cljc
src/asami/query.cljc
test/asami/api_test.cljc
test/asami/core_query_test.cljc
test/asami/durable/api_test.cljc

Also updating index filenames, as these had duplicate extensions

Fixing groups in aggregates

---

CHANGELOG.md
README.md
project.clj
src/asami/durable/graph.cljc
src/asami/durable/store.cljc
src/asami/graph.cljc
test/asami/durable/graph_test.cljc

The ID generator now correctly initializes from the latest transaction, and updates after imports

ID Generation

---

project.clj
src-native/asami/main.clj

A new profile that compiles src-native/asami/main.clj and builds a native image

Added a native command line utility

---

src/asami/entities/reader.cljc
test/asami/core_query_test.cljc
test/asami/entities/test_entity.cljc

Fixed issue in #159 where nested entities that referred back to earlier entities would loop indefinitely

Entity recursion

---

deps.edn
src/asami/durable/codec.cljc
src/asami/durable/decoder.clj
src/asami/durable/encoder.clj
src/asami/durable/graph.cljc
src/asami/durable/pool.cljc
src/asami/durable/store.cljc
src/asami/durable/tree.cljc
src/asami/durable/tuples.cljc
test/asami/durable/block_tree_test.cljc
test/asami/durable/codec_test.cljc
test/asami/durable/graph_test.cljc
test/asami/durable/object_codec_test.clj
test/asami/durable/pages_test.clj
test/asami/durable/tuples_test.cljc

This will simplify #137 
Closes #167

Merged block managers

---

src/asami/cache.cljc
src/asami/common_index.cljc
src/asami/durable/block/file/block_file.clj
src/asami/durable/pool.cljc
src/asami/durable/tree.cljc
src/asami/internal.cljc
test/asami/cache_test.cljc

Addresses bug in issue-182 and moved to log(n) complexity

Transitive restructure

---

src/asami/core.cljc
src/asami/durable/store.cljc
src/asami/memory.cljc
src/asami/storage.cljc
test/asami/durable/store_test.cljc

As per https://github.com/threatgrid/asami/issues/150
Added the as-of-time function which returns the timestamp saved for a
given database.

Added as-of-time

---

src/asami/projection.cljc
src/asami/query.cljc
test/asami/planner_test.cljc
test/asami/query_internals_test.cljc

Removed a few redundancies, and updated `asami.query` to use some of the redefinitions from `asami.projection` rather than `zuko.schema`

Imported projection operations from Zuko

---

src/asami/query.cljc
test/asami/query_internals_test.cljc

This patch does what the title suggests. 😄

Validate that variables in :find are bound
